import test from 'node:test';
import assert from 'node:assert/strict';
import {mkdtemp,rm} from 'node:fs/promises';
import {tmpdir} from 'node:os';
import {join} from 'node:path';
import {createApp} from '../server.mjs';
const origin='http://localhost',password='A-long-test-password-2026';
async function launch(dir,mail={}){const app=await createApp({dataDir:dir,siteUrl:origin,production:false,newsletter:{autoStart:false,enabled:true,apiKey:'re_test_only',from:'ATHENA <news@example.test>',...mail}});await new Promise(r=>app.server.listen(0,'127.0.0.1',r));return {...app,base:'http://127.0.0.1:'+app.server.address().port};}
async function post(app,path,body,cookie='',csrf=''){return fetch(app.base+path,{method:'POST',headers:{Origin:origin,'Content-Type':'application/json',Cookie:cookie,'X-CSRF-Token':csrf},body:JSON.stringify(body)});}
async function signup(app,email,emailUpdates=true){const response=await post(app,'/api/reader/signup',{email,password,consent:true,emailUpdates});assert.equal(response.status,200);const cookie=response.headers.get('set-cookie').split(';')[0],r=await (await fetch(app.base+'/api/reader/me',{headers:{Cookie:cookie}})).json();return {cookie,csrf:r.csrf,id:app.db.prepare('SELECT id FROM readers WHERE email=?').get(email).id};}
function publish(app,id,category='World',date='2026-10-02T00:00:00.000Z'){app.db.prepare('INSERT INTO articles(id,title,subtitle,category,author,body,status,updated,published_at) VALUES (?,?,?,?,?,?,?,?,?)').run(id,'An archive report','Verified context.',category,'ATHENA','A report.','published',date,date);}
function confirmationToken(app,id){const m=app.db.prepare("SELECT payload FROM mail_jobs WHERE reader_id=? AND kind='confirmation' ORDER BY created_at DESC LIMIT 1").get(id);return JSON.parse(m.payload).text.match(/\/email\/confirm\?token=([a-f0-9]{64})/)[1];}
test('Missing mail configuration blocks email promises while accounts remain functional',async()=>{
 const dir=await mkdtemp(join(tmpdir(),'athena-mail-off-'));const app=await launch(dir,{enabled:false,apiKey:'',fetch:()=>{throw Error('No email should be sent')}});try{const denied=await post(app,'/api/reader/signup',{email:'blocked@example.test',password,consent:true,emailUpdates:true});assert.equal(denied.status,503);assert.equal(app.db.prepare('SELECT COUNT(*) AS n FROM readers').get().n,0);const r=await signup(app,'account@example.test',false);assert.equal(app.newsletter.state(r.id).available,false);assert.equal((await post(app,'/api/reader/email-preferences',{emailUpdates:true},r.cookie,r.csrf)).status,503);publish(app,'no-mail-story');await app.newsletter.tick();assert.equal(app.db.prepare('SELECT COUNT(*) AS n FROM mail_jobs').get().n,0);}finally{await app.close();await rm(dir,{recursive:true,force:true})}
});
test('Confirmed opt-in, section filtering, original archive dates, deduplication and signed unsubscribe',async()=>{
 const dir=await mkdtemp(join(tmpdir(),'athena-mail-test-')),sent=[];const app=await launch(dir,{fetch:async(url,options)=>{sent.push({url,options,message:JSON.parse(options.body)});return {ok:true,status:200,json:async()=>({id:'accepted-'+sent.length})}}});try{
 const first=await signup(app,'reader@example.test'),other=await signup(app,'other@example.test',false),raw=confirmationToken(app,first.id);
 assert.equal(sent.length,0);const landing=await fetch(app.base+'/email/confirm?token='+raw);assert.equal(landing.status,200);assert.match(landing.headers.get('referrer-policy'),/no-referrer/);assert.match(landing.headers.get('x-robots-tag'),/noindex/);assert.equal(app.newsletter.state(first.id).verified,false);await app.newsletter.tick();assert.equal(sent.length,1);assert.equal(sent[0].message.to[0],'reader@example.test');assert.equal(app.newsletter.status().jobs[0].state,'accepted');
 assert.equal((await post(app,'/api/reader/email/confirm',{token:raw})).status,200);assert.equal((await post(app,'/api/reader/email/confirm',{token:raw})).status,400);assert(app.newsletter.state(first.id).verified);assert.equal(app.newsletter.state(other.id).optedIn,false);
 await post(app,'/api/reader/preferences',{sections:['World']},first.cookie,first.csrf);publish(app,'world-archive');publish(app,'culture-filtered','Culture');await app.newsletter.tick();assert.equal(sent.length,2);const delivered=sent[1].message;assert.deepEqual(delivered.to,['reader@example.test']);assert.match(delivered.subject,/ATHENA archive:/);assert.match(delivered.text,/Originally reported 2 October 2026/);assert.match(delivered.headers['List-Unsubscribe-Post'],/One-Click/);
 app.db.prepare("UPDATE articles SET title='Edited archive title' WHERE id='world-archive'").run();await app.newsletter.tick();assert.equal(sent.length,2);assert.equal(app.db.prepare('SELECT COUNT(*) AS n FROM mail_jobs WHERE article_id=?').get('world-archive').n,1);
 publish(app,'queued-before-stop');app.newsletter.scan();const unsub=app.db.prepare('SELECT unsubscribe_token FROM reader_mail WHERE reader_id=?').get(first.id).unsubscribe_token;assert.equal((await fetch(app.base+'/email/unsubscribe?token='+unsub)).status,200);assert(app.newsletter.state(first.id).optedIn);assert.equal((await fetch(app.base+'/email/unsubscribe?token='+unsub,{method:'POST',headers:{'Content-Type':'application/x-www-form-urlencoded'},body:'List-Unsubscribe=One-Click'})).status,200);assert(!app.newsletter.state(first.id).optedIn);await app.newsletter.tick();assert.equal(sent.length,2);assert.equal(app.db.prepare("SELECT state FROM mail_jobs WHERE article_id='queued-before-stop'").get().state,'cancelled');
 assert.equal((await post(app,'/api/reader/delete',{password,confirm:true},first.cookie,first.csrf)).status,200);assert.equal(app.db.prepare('SELECT COUNT(*) AS n FROM mail_jobs WHERE reader_id=?').get(first.id).n,0);
 }finally{await app.close();await rm(dir,{recursive:true,force:true})}
});
test('Mail retries survive restart with stable payload and idempotency; provider failures are held',async()=>{
 const dir=await mkdtemp(join(tmpdir(),'athena-mail-retry-')),requests=[];let app=await launch(dir,{fetch:async(_,o)=>{requests.push(o);throw Error('Temporary network outage')}});try{
 const r=await signup(app,'retry@example.test');await app.newsletter.tick();let job=app.db.prepare('SELECT * FROM mail_jobs').get();assert.equal(job.state,'pending');assert.equal(job.error_code,'network-error');assert.equal(job.attempts,1);await app.close();
 app=await launch(dir,{fetch:async(_,o)=>{requests.push(o);return {ok:true,status:200,json:async()=>({id:'same-message'})}}});app.db.prepare('UPDATE mail_jobs SET due_at=0 WHERE id=?').run(job.id);await app.newsletter.tick();assert.equal(requests.length,2);assert.equal(requests[0].body,requests[1].body);assert.equal(requests[0].headers['Idempotency-Key'],requests[1].headers['Idempotency-Key']);assert.equal(app.db.prepare('SELECT state FROM mail_jobs WHERE id=?').get(job.id).state,'accepted');
 await post(app,'/api/reader/email/confirm',{token:confirmationToken(app,r.id)});publish(app,'late-retry');app.newsletter.scan();job=app.db.prepare("SELECT * FROM mail_jobs WHERE article_id='late-retry'").get();app.db.prepare('UPDATE mail_jobs SET first_attempt_at=? WHERE id=?').run(Date.now()-24*3600000,job.id);await app.newsletter.tick();assert.equal(app.db.prepare('SELECT state,error_code FROM mail_jobs WHERE id=?').get(job.id).error_code,'retry-window-expired');assert.equal(requests.length,2);
 app.newsletter.unsubscribe(r.id);assert.equal(app.db.prepare("SELECT state FROM mail_jobs WHERE article_id='late-retry'").get().state,'cancelled');
 }finally{await app.close();await rm(dir,{recursive:true,force:true})}
});
