import {randomUUID} from 'node:crypto';
import {digest,token,hashPassword,verifyPassword} from './auth.mjs';
import {layout,esc,categories} from './views.mjs';
const emailField='<label>Email address<input name="email" type="email" autocomplete="email" required maxlength="254"></label>';
const passwordField='<label>Password<input name="password" type="password" autocomplete="current-password" required minlength="14" maxlength="256"></label>';
function page(content){return layout(`<main id="content" class="member-page">${content}<p id="member-notice" role="status"></p></main>`,{title:'Your ATHENA account',noindex:true,script:'/members.js'})}
export function memberPage(kind){
 if(kind==='account')return page(`<div class="eyebrow">ATHENA / YOUR NEWS</div><h1>Your perspective. Your stories.</h1><p id="member-email"></p><div id="recovery-box" hidden><h2>Save your recovery code</h2><p>This code is shown once. Keep it somewhere private. You need it to reset a forgotten password while email recovery is unavailable.</p><code id="recovery-code"></code><button id="copy-recovery" class="outline-button">Copy code</button><button id="saved-recovery" class="outline-button">I have saved it</button></div><div class="member-actions"><button id="member-logout" class="outline-button">Sign out</button><a href="/">Visit the newsroom ↗</a></div><section class="member-settings"><h2>Choose your news sections</h2><form id="preferences-form"><fieldset><legend>Select at least one section</legend>${categories.map(c=>`<label class="check"><input type="checkbox" name="sections" value="${c}">${c}</label>`).join('')}</fieldset><button class="black-button">Save preferences</button></form><p>News updates appear here automatically while this page is open. Email updates are not available yet.</p></section><section><div class="member-actions"><h2>Your news feed <span id="unread-count"></span></h2><button id="mark-all" class="outline-button">Mark all as read</button><button id="refresh-feed" class="outline-button">Refresh</button></div><p id="feed-status" role="status">Loading your stories…</p><div id="member-feed"></div></section><details class="member-settings"><summary>Account security and deletion</summary><h2>Change password</h2><form id="change-password-form">${passwordField.replace('Password','Current password')}<label>New password<input name="newPassword" type="password" autocomplete="new-password" minlength="14" maxlength="256" required></label><button class="outline-button">Change password</button></form><h2>Delete account</h2><p>Permanently removes your account, preferences and reading history.</p><form id="delete-account-form">${passwordField}<label class="check"><input type="checkbox" name="confirm" required>I want to permanently delete my account.</label><button class="outline-button">Delete my account</button></form></details>`);
 if(kind==='recover')return page(`<div class="eyebrow">ATHENA / ACCOUNT RECOVERY</div><h1>Get back to your news.</h1><p>Use the recovery code you saved when creating your account.</p><form id="recover-form">${emailField}<label>Recovery code<input name="recovery" autocomplete="off" required maxlength="64"></label><label>New password<input name="newPassword" type="password" autocomplete="new-password" required minlength="14" maxlength="256"></label><button class="black-button">Reset password</button></form><p><a href="/signin">Back to sign in</a></p>`);
 if(kind==='signin')return page(`<div class="eyebrow">ATHENA / READER SIGN IN</div><h1>Welcome back.</h1><form id="signin-form">${emailField}${passwordField}<button class="black-button">Sign in</button></form><p><a href="/recover">Forgot password?</a> · <a href="/subscribe">Create an account</a></p>`);
 return page(`<div class="eyebrow">ATHENA / JOIN THE READERS</div><h1>Stay close to the stories that matter.</h1><p>Create your free ATHENA account. Follow the sections you care about and see new stories in your personal news feed.</p><form id="signup-form">${emailField}${passwordField.replace('current-password','new-password')}<p class="optional">Use at least 14 characters. You’ll receive a private recovery code after signup.</p><label class="check"><input name="consent" type="checkbox" required>I agree to the <a href="/reader-privacy">reader privacy notice</a>.</label><button class="black-button">Create free account</button></form><p>Already a reader? <a href="/signin">Sign in</a></p><p class="optional">Updates appear inside your account. Email delivery is not yet available. No payment required.</p>`);
}
export function readerPrivacy(){return layout(`<main id="content" class="member-page"><h1>Reader privacy</h1><p>ATHENA stores your email address, securely hashed password and recovery code, news-section preferences, and which stories you have marked as read to provide your reader account. We use an essential session cookie to keep you signed in for up to 30 days.</p><p>Your reading history and account details are private and are not displayed to other readers. No marketing emails are sent through this signup. Email updates will require a separate opt-in when available.</p><p>You can delete your account and its associated records in your account settings. Security rate-limit records are retained temporarily to protect sign-in. Contact ATHENA at otravelscope@gmail.com with account or privacy questions.</p><p><a href="/subscribe">Create an account</a> · <a href="/account">Your account</a></p></main>`,{title:'Reader privacy | ATHENA'})}
export async function createMembers({db,siteUrl,production,send,json,readJSON,originCheck}){
 db.exec(`CREATE TABLE IF NOT EXISTS readers(id TEXT PRIMARY KEY,email TEXT NOT NULL UNIQUE,password_hash TEXT NOT NULL,recovery_hash TEXT NOT NULL,sections TEXT NOT NULL,created_at TEXT NOT NULL);
 CREATE TABLE IF NOT EXISTS reader_sessions(hash TEXT PRIMARY KEY,reader_id TEXT NOT NULL REFERENCES readers(id) ON DELETE CASCADE,csrf TEXT NOT NULL,expires INTEGER NOT NULL);
 CREATE TABLE IF NOT EXISTS reader_reads(reader_id TEXT NOT NULL REFERENCES readers(id) ON DELETE CASCADE,article_id TEXT NOT NULL,PRIMARY KEY(reader_id,article_id));
 CREATE TABLE IF NOT EXISTS reader_limits(key TEXT PRIMARY KEY,attempts INTEGER NOT NULL,expires INTEGER NOT NULL);`);
 const cookieName=siteUrl.startsWith('https:')?'__Host-athena_reader':'athena_reader';
 const dummy=await hashPassword(token());let hashing=0;
 function fail(status,message){const e=new Error(message);e.status=status;throw e}
 function cookie(value,seconds){return `${cookieName}=${value}; Path=/; HttpOnly; SameSite=Strict; Max-Age=${seconds}${siteUrl.startsWith('https:')?'; Secure':''}`}
 function session(req){const raw=String(req.headers.cookie||'').split(';').map(s=>s.trim()).find(s=>s.startsWith(cookieName+'='))?.slice(cookieName.length+1);if(!raw||!/^[a-f0-9]{64}$/.test(raw))return null;return db.prepare('SELECT s.*,r.email,r.sections FROM reader_sessions s JOIN readers r ON r.id=s.reader_id WHERE s.hash=? AND s.expires>?').get(digest(raw),Date.now())}
 function requireReader(req){const s=session(req);if(!s)fail(401,'Sign in to your reader account.');return s}
 function csrf(req,s){originCheck(req);if(req.headers['x-csrf-token']!==s.csrf)fail(403,'Reload your account page and try again.')}
 function limit(key,max=10){const now=Date.now();db.prepare('DELETE FROM reader_limits WHERE expires<?').run(now);const k=digest(key),r=db.prepare('SELECT * FROM reader_limits WHERE key=?').get(k);if(r&&r.attempts>=max)fail(429,'Too many attempts. Try again in 15 minutes.');db.prepare('INSERT INTO reader_limits VALUES(?,?,?) ON CONFLICT(key) DO UPDATE SET attempts=attempts+1').run(k,1,now+900000)}
 function ip(req){return production?String(req.headers['x-forwarded-for']||req.socket.remoteAddress).split(',').at(-1).trim():req.socket.remoteAddress}
 async function expensive(fn){if(hashing>=3)fail(429,'Sign-in is busy. Please try again shortly.');hashing++;try{return await fn()}finally{hashing--}}
 function credentials(p){const email=typeof p.email==='string'?p.email.trim().toLowerCase():'';if(!/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(email)||email.length>254)fail(400,'Enter a valid email address.');return email}
 function newPassword(value){if(typeof value!=='string'||value.length<14||value.length>256)fail(400,'Use a password between 14 and 256 characters.')}
 function issue(req,res,id,extra={}){const old=session(req);if(old)db.prepare('DELETE FROM reader_sessions WHERE hash=?').run(old.hash);db.prepare('DELETE FROM reader_sessions WHERE expires<?').run(Date.now());const raw=token(),csrfToken=token();db.prepare('INSERT INTO reader_sessions VALUES(?,?,?,?)').run(digest(raw),id,csrfToken,Date.now()+30*86400000);json(res,200,{ok:true,...extra},{'Set-Cookie':cookie(raw,30*86400)})}
 return async function handle(req,res,path){
 if(!['/subscribe','/signin','/account','/recover','/reader-privacy'].includes(path)&&!path.startsWith('/api/reader/'))return false;
 try{
 if(req.method==='GET'&&path==='/reader-privacy'){send(res,200,readerPrivacy());return true}
 if(req.method==='GET'&&['/subscribe','/signin','/account','/recover'].includes(path)){const s=session(req);if(path==='/account'&&!s){send(res,303,'','text/plain',{Location:'/signin'});return true}if(s&&['/subscribe','/signin'].includes(path)){send(res,303,'','text/plain',{Location:'/account'});return true}send(res,200,memberPage(path==='/account'?'account':path==='/signin'?'signin':path==='/recover'?'recover':'signup'));return true}
 if(req.method==='POST'&&['/api/reader/signup','/api/reader/signin','/api/reader/recover'].includes(path)){
 originCheck(req);limit('ip:'+ip(req),40);const p=await readJSON(req,10000);if(!p||typeof p!=='object')fail(400,'Invalid request.');const email=credentials(p);limit(path+':'+email,8);
 if(path.endsWith('/signup')){if(p.consent!==true)fail(400,'Please agree to the reader privacy notice.');newPassword(p.password);const hash=await expensive(()=>hashPassword(p.password)),recovery=token();const id=randomUUID();const result=db.prepare('INSERT OR IGNORE INTO readers VALUES(?,?,?,?,?,?)').run(id,email,hash,digest(recovery),JSON.stringify(categories),new Date().toISOString());if(!result.changes)fail(409,'Unable to create an account with those details. Try signing in or recovering your account.');issue(req,res,id,{recovery});return true}
 const r=db.prepare('SELECT * FROM readers WHERE email=?').get(email);
 if(path.endsWith('/signin')){const valid=await expensive(()=>verifyPassword(p.password,r?.password_hash||dummy));if(!valid||!r)fail(401,'Email or password is incorrect.');issue(req,res,r.id);return true}
 newPassword(p.newPassword);if(!r||typeof p.recovery!=='string'||p.recovery.length>64||digest(p.recovery.trim())!==r.recovery_hash)fail(401,'Email or recovery code is incorrect.');const hash=await expensive(()=>hashPassword(p.newPassword));const recovery=token();db.exec('BEGIN');try{const changed=db.prepare('UPDATE readers SET password_hash=?,recovery_hash=? WHERE id=? AND recovery_hash=?').run(hash,digest(recovery),r.id,r.recovery_hash);if(!changed.changes)fail(409,'Recovery code already used.');db.prepare('DELETE FROM reader_sessions WHERE reader_id=?').run(r.id);db.exec('COMMIT')}catch(e){db.exec('ROLLBACK');throw e}issue(req,res,r.id,{recovery});return true;
 }
 const s=requireReader(req);
 if(req.method==='GET'&&path==='/api/reader/me'){json(res,200,{email:s.email,sections:JSON.parse(s.sections),csrf:s.csrf});return true}
 if(req.method==='GET'&&path==='/api/reader/feed'){const allowed=new Set(JSON.parse(s.sections));const rows=db.prepare("SELECT a.id,a.title,a.subtitle,a.category,a.published_at,CASE WHEN rr.article_id IS NULL THEN 1 ELSE 0 END AS unread FROM articles a LEFT JOIN reader_reads rr ON rr.article_id=a.id AND rr.reader_id=? WHERE a.status='published' ORDER BY a.published_at DESC LIMIT 500").all(s.reader_id).filter(a=>allowed.has(a.category));json(res,200,{articles:rows});return true}
 if(req.method!=='POST')fail(405,'Method not allowed.');csrf(req,s);const p=await readJSON(req,10000);
 if(path==='/api/reader/preferences'){if(!Array.isArray(p.sections)||!p.sections.length||p.sections.length>categories.length||p.sections.some(c=>!categories.includes(c)))fail(400,'Choose at least one valid news section.');db.prepare('UPDATE readers SET sections=? WHERE id=?').run(JSON.stringify([...new Set(p.sections)]),s.reader_id);json(res,200,{ok:true});return true}
 if(path==='/api/reader/read'){if(!Array.isArray(p.ids)||p.ids.length>500||p.ids.some(id=>typeof id!=='string'||id.length>100))fail(400,'Invalid stories.');const mark=db.prepare("INSERT OR IGNORE INTO reader_reads SELECT ?,id FROM articles WHERE id=? AND status='published'");for(const id of p.ids)mark.run(s.reader_id,id);json(res,200,{ok:true});return true}
 if(path==='/api/reader/logout'){db.prepare('DELETE FROM reader_sessions WHERE hash=?').run(s.hash);json(res,200,{ok:true},{'Set-Cookie':cookie('',0)});return true}
 if(['/api/reader/password','/api/reader/delete'].includes(path)){limit('sensitive:'+s.reader_id,8);const r=db.prepare('SELECT * FROM readers WHERE id=?').get(s.reader_id);if(!await expensive(()=>verifyPassword(p.password,r.password_hash)))fail(401,'Current password is incorrect.');
 if(path.endsWith('/delete')){if(p.confirm!==true)fail(400,'Confirm account deletion.');db.prepare('DELETE FROM readers WHERE id=?').run(s.reader_id);json(res,200,{ok:true},{'Set-Cookie':cookie('',0)});return true}
 newPassword(p.newPassword);const hash=await expensive(()=>hashPassword(p.newPassword));db.prepare('UPDATE readers SET password_hash=? WHERE id=?').run(hash,s.reader_id);db.prepare('DELETE FROM reader_sessions WHERE reader_id=?').run(s.reader_id);issue(req,res,s.reader_id);return true}
 fail(404,'Page not found.');
 }catch(e){if(e.status)json(res,e.status,{error:e.message});else{console.error('Reader request failed');json(res,500,{error:'Could not complete the request. Please try again.'})}return true
 };
}

}
