const xml=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&apos;'}[c]));
export const sectionPath=section=>'/section/'+section.toLowerCase();
export const articleUrl=(a,siteUrl)=>siteUrl+'/article/'+encodeURIComponent(a.id);
export function absoluteImage(value,siteUrl){try{const u=new URL(value,siteUrl);return ['https:','http:'].includes(u.protocol)&&!u.username&&!u.password?u.href:''}catch{return ''}}
export function jsonLD(value){return JSON.stringify(value).replace(/</g,'\\u003c').replace(/>/g,'\\u003e').replace(/&/g,'\\u0026');}
export function websiteSchema(siteUrl){return {'@context':'https://schema.org','@graph':[
 {'@type':'NewsMediaOrganization','@id':siteUrl+'/#publisher',name:'ATHENA',url:siteUrl+'/',logo:siteUrl+'/favicon.svg',description:'Independent reporting and perspectives with women and children at the centre of the story.',email:'otravelscope@gmail.com'},
 {'@type':'WebSite','@id':siteUrl+'/#website',name:'ATHENA',url:siteUrl+'/',publisher:{'@id':siteUrl+'/#publisher'},inLanguage:'en',description:'Global news, culture and perspectives concerning women and children.'}
]};}
export function articleSchema(a,siteUrl){
 const url=articleUrl(a,siteUrl);const photos=[a.image,...[...a.body.matchAll(/^!\[[^\]]*\]\((https:\/\/[^\s)]+)\)/gm)].map(m=>m[1])].filter(Boolean).map(v=>absoluteImage(v,siteUrl)).filter(Boolean);
 const author=a.author||'ATHENA';return {'@context':'https://schema.org','@type':a.category==='Perspectives'?'Article':'NewsArticle','@id':url+'#article',mainEntityOfPage:{'@type':'WebPage','@id':url},url,headline:a.title,description:a.subtitle,articleSection:a.category,inLanguage:'en',datePublished:new Date(a.published_at||a.updated).toISOString(),dateModified:new Date(a.updated).toISOString(),author:author==='ATHENA'?{'@type':'Organization',name:author,url:siteUrl+'/about'}:{'@type':'Person',name:author},publisher:{'@type':'NewsMediaOrganization','@id':siteUrl+'/#publisher',name:'ATHENA',url:siteUrl+'/',logo:{'@type':'ImageObject',url:siteUrl+'/favicon.svg'}},...(photos.length?{image:[...new Set(photos)]}:{}),isAccessibleForFree:true};
}
export function sitemapXML(articles,siteUrl,categories){const pages=['/','/about','/contact','/subscribe','/reader-privacy',...categories.map(sectionPath)];return '<?xml version="1.0" encoding="UTF-8"?><urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">'+pages.map(p=>'<url><loc>'+xml(siteUrl+p)+'</loc></url>').join('')+articles.map(a=>'<url><loc>'+xml(articleUrl(a,siteUrl))+'</loc><lastmod>'+xml(new Date(a.updated).toISOString())+'</lastmod></url>').join('')+'</urlset>';}
export function newsSitemapXML(articles,siteUrl,now=Date.now()){return '<?xml version="1.0" encoding="UTF-8"?><urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9" xmlns:news="http://www.google.com/schemas/sitemap-news/0.9">'+articles.filter(a=>a.category!=='Perspectives'&&Date.parse(a.published_at||a.updated)>=now-2*86400000&&Date.parse(a.published_at||a.updated)<=now).slice(0,1000).map(a=>'<url><loc>'+xml(articleUrl(a,siteUrl))+'</loc><news:news><news:publication><news:name>ATHENA</news:name><news:language>en</news:language></news:publication><news:publication_date>'+xml(new Date(a.published_at||a.updated).toISOString())+'</news:publication_date><news:title>'+xml(a.title)+'</news:title></news:news></url>').join('')+'</urlset>';}
export function rssXML(articles,siteUrl){return '<?xml version="1.0" encoding="UTF-8"?><rss version="2.0" xmlns:atom="http://www.w3.org/2005/Atom"><channel><title>ATHENA — News &amp; Perspectives</title><link>'+xml(siteUrl+'/')+'</link><description>Women and children at the centre of the story.</description><language>en</language><atom:link href="'+xml(siteUrl+'/feed.xml')+'" rel="self" type="application/rss+xml"/>'+articles.slice(0,100).map(a=>'<item><title>'+xml(a.title)+'</title><link>'+xml(articleUrl(a,siteUrl))+'</link><guid isPermaLink="true">'+xml(articleUrl(a,siteUrl))+'</guid><description>'+xml(a.subtitle)+'</description><category>'+xml(a.category)+'</category><pubDate>'+xml(new Date(a.published_at||a.updated).toUTCString())+'</pubDate></item>').join('')+'</channel></rss>';}
